import {test,expect} from '@playwright/test';
import JSZip from 'jszip';

test('reader comments require sign-in and render provider data as plain text',async({page})=>{
  await page.goto('/');await page.evaluate(async()=>{const {createReaderComments}=await import('/src/reader-comments.js');const root=document.createElement('section'),content=document.createElement('div');content.textContent='Published passage';document.body.replaceChildren(content,root);let user=null;const comments=[];const remote={async readerComments(){return {enabled:true,version:'v1',comments}},async writeReaderComment(_token,_chapter,operation,values){if(operation==='create')comments.push({id:'one',author:'Reader',body:values.body,quote:values.quote,mine:true,canDelete:true,outdated:false});}};window.__readerFixture={setUser(value){user=value;}};window.__readerComments=createReaderComments({root,content,remote,getUser:()=>user,signIn:()=>root.dataset.signIn='requested',onInvalid:()=>{}});await window.__readerComments.open('token','chapter');});
  await page.getByRole('textbox',{name:'Comment'}).fill('<img src=x onerror=alert(1)>');await page.getByRole('button',{name:'Post comment'}).click();await expect(page.locator('section')).toHaveAttribute('data-sign-in','requested');await expect(page.locator('.reader-comment')).toHaveCount(0);await page.evaluate(()=>window.__readerFixture.setUser({id:'reader'}));await page.getByRole('button',{name:'Post comment'}).click();await expect(page.locator('.reader-comment p')).toHaveText('<img src=x onerror=alert(1)>');await expect(page.locator('.reader-comment img')).toHaveCount(0);
});

test('translated EPUB publishes approved ruby as escaped XHTML',async({page})=>{
  const zip=new JSZip();zip.file('mimetype','application/epub+zip');zip.file('META-INF/container.xml','<container><rootfiles><rootfile full-path="OEBPS/book.opf"/></rootfiles></container>');zip.file('OEBPS/book.opf','<package><manifest><item href="one.xhtml" media-type="application/xhtml+xml" id="one"/></manifest><spine><itemref idref="one"/></spine></package>');zip.file('OEBPS/one.xhtml','<html xmlns="http://www.w3.org/1999/xhtml"><body><p>source</p></body></html>');const source=(await zip.generateAsync({type:'nodebuffer'})).toString('base64');await page.goto('/');
  const output=await page.evaluate(async encoded=>{const {buildTranslatedEpub}=await import('/src/epub-reader.js');const bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));const snapshot={novel:{chapters:[{id:'one',xhtmlPath:'OEBPS/one.xhtml'}]},translations:{one:'Tokyo is calm.'},exportExcluded:[],publishedRuby:{one:[{start:0,end:5,reading:'<img onerror=alert(1)>'}]}};const result=new Uint8Array(await (await buildTranslatedEpub(new File([bytes],'book.epub'),snapshot)).arrayBuffer());let binary='';for(let i=0;i<result.length;i+=0x8000)binary+=String.fromCharCode(...result.subarray(i,i+0x8000));return btoa(binary);},source);
  const exported=await JSZip.loadAsync(Buffer.from(output,'base64')),markup=await exported.file('OEBPS/one.xhtml').async('string');expect(markup).toContain('<ruby>Tokyo<rt>&lt;img onerror=alert(1)&gt;</rt></ruby>');expect(markup).not.toContain('<img onerror=');
});
